services:
  - type: web
    name: greenlot
    env: node
    rootDir: GREENLOT-main
    buildCommand: npm ci --omit=dev
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
